### ISSUE TITLE
Apex Legends

### ISSUE THREAD

**Issue by gazornuh** [InstinctEx/ReChecker#1]
Why is there no way to bypass EAC in Apex Legends? It is even possible? And one little question, they banned reWASD specially or they just broke something and reWASD don't work?

**Comment by InstinctEx** [comment]
I'm sure there is a way I just don't have the time right now to implement it. You are more than welcome to fork and make it yourself!

**Comment by josafatex12** [comment]
i hope this can help u for source code
https://github.com/EugeneSunrise/reWASD

**Comment by InstinctEx** [comment]
> i hope this can help u for source code https://github.com/EugeneSunrise/reWASD

This does not include the driver, thanks for the information though !
