### ISSUE TITLE
"Cannot Create a File When the File Already Exists"

### ISSUE THREAD

**Issue by rg2323** [InstinctEx/ReChecker#4]
Getting these errors when trying to run ReChecker.

ReWasd is closing fully before I click run, and I'm running ReChecker as admin. 

<img width="328" alt="1" src="https://github.com/InstinctEx/ReChecker/assets/113138509/8f3ac698-01bf-45e7-b2a9-8fb09d69a5ec">
<img width="314" alt="2" src="https://github.com/InstinctEx/ReChecker/assets/113138509/aef680a8-814f-4dd9-b820-6628dc4defd8">

**Comment by rg2323** [comment]
I've also tried stopping the Rewasd service in the Task manager "Services" section, but literally nothing I try works.

**Comment by InstinctEx** [comment]
Found out what the issue is, making a fix and uploading when I can.

**Comment by InstinctEx** [comment]
Fixed in latest release!
